version: '2.3'

services:
  postgres:
    image: postgres:10.8-alpine
    container_name: postgres-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "4200:5432"
    volumes:
      - ./shared_data:/shared_data
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  # Model Set 1 Services
  melody_generation_set1:
    build:
      context: ./model-set-1/tmik_bgm_conditional_melody_generation
      dockerfile: Dockerfile
    container_name: melody-generation-set1
    restart: unless-stopped
    environment:
      - CHECKPOINT_PATH=/app/checkpoints/checkpoint.pth
      - BGMPATH=/app/testdata/test.mid
      - GEN_SEED=0
      - MODEL_SET=set1
    volumes:
      - ./shared_data:/shared_data
      - ./model-set-1/tmik_bgm_conditional_melody_generation:/app
    command: ["tail", "-f", "/dev/null"]  # Keeps container running
    depends_on:
      - postgres
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vocal_mix_set1:
    build:
      context: ./model-set-1/tmik_make_vocal_mix
      dockerfile: Dockerfile
    container_name: vocal-mix-set1
    restart: unless-stopped
    environment:
      - DREAMTONICS_SDK_PATH=/app/dreamtonics_sdk
      - SEX=female
      - MODEL_SET=set1
    volumes:
      - ./shared_data:/shared_data
      - ./model-set-1/tmik_make_vocal_mix:/app
    command: ["tail", "-f", "/dev/null"]  # Keeps container running
    depends_on:
      - postgres
      - melody_generation_set1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Model Set 2 Services
  # melody_generation_set2:
  #   build:
  #     context: ./model-set-2/tmik_melody_generation
  #     dockerfile: Dockerfile
  #   container_name: melody-generation-set2
  #   restart: unless-stopped
  #   environment:
  #     - CHECKPOINT_PATH=/app/checkpoints/checkpoint.pth
  #     - BGMPATH=/app/testdata/test.mid
  #     - GEN_SEED=0
  #     - MODEL_SET=set2
  #   volumes:
  #     - ./shared_data:/shared_data
  #     - ./model-set-2/tmik_melody_generation:/app
  #   command: ["tail", "-f", "/dev/null"]  # Keeps container running
  #   depends_on:
  #     - postgres
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

  # vocal_mix_set2:
  #   build:
  #     context: ./model-set-2/tmik_vocalmix
  #     dockerfile: Dockerfile
  #   container_name: vocal-mix-set2
  #   restart: unless-stopped
  #   environment:
  #     - DREAMTONICS_SDK_PATH=/app/dreamtonics_sdk
  #     - SEX=female
  #     - MODEL_SET=set2
  #   volumes:
  #     - ./shared_data:/shared_data
  #     - ./model-set-2/tmik_vocalmix:/app
  #   command: ["tail", "-f", "/dev/null"]  # Keeps container running
  #   depends_on:
  #     - postgres
  #     - melody_generation_set2
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

  integrated_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: integrated-app
    restart: unless-stopped
    ports:
      - "80:7860"  # Map host port 80 to container port 7860
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-database:5432/mydb
      - MELODY_GEN_SET1_SERVICE=melody-generation-set1
      - VOCAL_MIX_SET1_SERVICE=vocal-mix-set1
      # - MELODY_GEN_SET2_SERVICE=melody-generation-set2
      # - VOCAL_MIX_SET2_SERVICE=vocal-mix-set2
    volumes:
      - ./shared_data:/shared_data
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    depends_on:
      - postgres
      - melody_generation_set1
      - vocal_mix_set1
      # - melody_generation_set2
      # - vocal_mix_set2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  db-data: