# melody token configs
pad_token: "PAD"
eos_token: "EOS"
bos_token: "BOS"
rest_token: "REST"
longrest_token: "LONGREST"
mask_token: "MASK"
note_prefix: "Note"
note_on_suffix: "On"
note_sustain_suffix: "Sus"
min_pitch: 0
max_pitch: 128
longrest_th: 32
use_longrest_token: true

# encoding config
bpm_boundaries: [50, 70, 90, 110, 130, 150, 170, 190]

# midi configs
beats_per_bar_candidates: [4]
resolution: 480
target_tracks: [0]
quantization_unit: 16

# fft configs
spectrogram_n_fft: 2048
spectrogram_hop_length: 256
chroma_n_fft: 2048
chroma_hop_length: 512

# cqt config
use_cqt: true
cqt_n_chroma: 12
cqt_n_octaves: 7
cqt_bins_per_octave: 36
cqt_mode: "full"

# rms configs
rms_frame_length: 2048
rms_hop_length: 512

# other configs
minimum_note_length: 1
dataaug_midi_file_suffix: ".mid"
dataaug_audio_file_suffix: ".mp3"
librosa_min_db: 80
min_count_unit: 0.25
counting_onehot_vec_size: 16
voiced_flags_scope_range: 16
audio_extensions: [".mp3", ".wav"]
midi_extensions: [".mid", ".midi"]
min_sixteenth_num: 16
cond_list_key: "cond_list"
attention_mask_list_key: "attention_mask_list"
actual_length_list_key: "actual_length_list"

# dataset configs
input_tensors_key: "input_tensors"
integrated_chroma_key: "integrated_chroma"
counting_onehot_vecs_key: "counting_onehot_vecs"
bpm_onehot_vecs_key: "bpm_onehot_vecs"
relative_rms_key: "relative_rms"
ranged_voiced_flags_key: "ranged_voiced_flags"
labels_key: "labels"
slice_length: 768
transformers_condition_key: "cond"
transformers_token_key: "xt"
transformers_time_key: "t"
transformers_attention_mask_key: "attention_mask"
transformers_labels_key: "labels"
diffusion_T: 100
mask_ratio_schedule: "linear"

# train configs
checkpoint_base_dirpath: "./checkpoints"
checkpoint_name: "test_rvf_lr"
train_source_dirpath: "./testdata/for_train_test/train_tensors"
eval_source_dirpath: "./testdata/for_train_test/eval_tensors"
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
num_train_epochs: 100
eval_strategy: "steps"
save_total_limit: 200
load_best_model_at_end: true
early_stopping_patience: 10000
save_steps: 10000
initial_checkpoint: null

# model configs
cond_size: 39
input_dense_dropout_prob: 0.1
input_dense_layer_norm_eps: !!float 1e-12
d_ff: 2048
d_model: 512
num_decoder_layers: 6
num_heads: 8
num_layers: 6
relative_attention_num_buckets: 768
relative_attention_max_distance: 1536

# beat estimation configs
dbe_model_type: "madmom_dbn_and_rnn"
dbe_clip: false
dbe_auto_adjust: false

# infer configs
infer_batch_size: 4
output_midi_program_num: 80
fixed_velocity: 100
write_midi_file_suffix: ".mid"
write_audio_file_suffix: ".mp3"
synth_demo_bgm_weight: 1
synth_demo_melody_weight: 1
do_lufs_normalize: true
top_k_ratio: 0.075
top_p: 0.95

# data augment configs
vocal_min_pitch: 41
vocal_max_pitch: 81
plus_pitch_shift_offset_max: 2
minus_pitch_shift_offset_max: 2